# Generated by Django 4.0.7 on 2024-08-31 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
